model:
  n_estimators: 100
  random_state: 42
  max_depth: 20
  max_features: 15
split:
  test_size: 0.2
  random_state: 42
mlflow:
  host: "128.0.1.1:8080"
  experiment: "roman_byelyy_mlops_hw2"
  run_name: "rbyelyy_run"
